/**
 * Generate shared test vectors for cross-language signing verification.
 *
 * Uses private key 0x01 (secp256k1 generator point) which both
 * @noble/secp256k1 and coincurve agree on.
 *
 * Run: npm run generate-vectors
 */

import { schnorr, etc } from '@noble/secp256k1';
import { sha256Hex } from '../src/hash.js';
import { serializeEvent, computeEventId, signEvent } from '../src/nostr/event.js';
import { signMessage } from '../src/nostr/message.js';
import { getPublicKeyHex } from '../src/nostr/identity.js';
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const PRIVATE_KEY_HEX = '0000000000000000000000000000000000000000000000000000000000000001';
const privateKey = etc.hexToBytes(PRIVATE_KEY_HEX);
const publicKey = getPublicKeyHex(privateKey);

console.log(`Private key: ${PRIVATE_KEY_HEX}`);
console.log(`Public key:  ${publicKey}`);

// Verify it's the expected generator point
const EXPECTED_PUBKEY = '79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798';
if (publicKey !== EXPECTED_PUBKEY) {
  throw new Error(`Unexpected public key: ${publicKey}`);
}

interface EventVector {
  name: string;
  unsigned: {
    pubkey: string;
    created_at: number;
    kind: number;
    tags: string[][];
    content: string;
  };
  expectedSerialized: string;
  expectedEventId: string;
  expectedSig: string;
}

interface MessageVector {
  name: string;
  message: string;
  expectedHash: string;
  expectedSig: string;
}

async function generateEventVector(
  name: string,
  kind: number,
  tags: string[][],
  content: string,
  created_at: number = 1700000000
): Promise<EventVector> {
  const unsigned = { pubkey: publicKey, created_at, kind, tags, content };
  const serialized = serializeEvent(unsigned);
  const signed = await signEvent(unsigned, privateKey);

  return {
    name,
    unsigned,
    expectedSerialized: serialized,
    expectedEventId: signed.id,
    expectedSig: signed.sig,
  };
}

async function generateMessageVector(name: string, message: string): Promise<MessageVector> {
  const { messageHash, signature } = await signMessage(message, privateKey);
  return { name, message, expectedHash: messageHash, expectedSig: signature };
}

async function main() {
  const events: EventVector[] = [];
  const messages: MessageVector[] = [];

  // Event 1: Civic voice support (Kind 30800)
  events.push(
    await generateEventVector(
      'civic_voice_support',
      30800,
      [
        ['d', 'decision:city-san-rafael:2026-01-15:item-3b'],
        ['j', 'city-san-rafael'],
        ['stance', 'support'],
      ],
      'civicos:voice:v1:decision:city-san-rafael:2026-01-15:item-3b:support:1700000000'
    )
  );

  // Event 2: Civic voice oppose (Kind 30800)
  events.push(
    await generateEventVector(
      'civic_voice_oppose',
      30800,
      [
        ['d', 'decision:city-san-rafael:2026-01-15:item-7a'],
        ['j', 'city-san-rafael'],
        ['stance', 'oppose'],
      ],
      'civicos:voice:v1:decision:city-san-rafael:2026-01-15:item-7a:oppose:1700000000'
    )
  );

  // Event 3: Comment (Kind 30803)
  events.push(
    await generateEventVector(
      'civic_comment',
      30803,
      [
        ['d', 'decision:city-san-rafael:2026-01-15:item-3b'],
        ['j', 'city-san-rafael'],
        ['stance', 'support'],
      ],
      'This housing proposal will help our community grow sustainably.'
    )
  );

  // Event 4: Empty content event (edge case)
  events.push(
    await generateEventVector('empty_content', 30800, [['d', 'test-entity'], ['j', 'test']], '')
  );

  // Event 5: Unicode content
  events.push(
    await generateEventVector(
      'unicode_content',
      30803,
      [
        ['d', 'test-unicode'],
        ['j', 'test'],
      ],
      'Supporto para vivienda asequible \u2014 \u00a1s\u00ed!'
    )
  );

  // Message 1: Action commitment
  messages.push(
    await generateMessageVector(
      'action_commitment',
      'civicos:action:v1:attend-council-meeting-2026-01-15:commitment'
    )
  );

  // Message 2: Initiative creation
  messages.push(
    await generateMessageVector(
      'initiative_creation',
      'civicos:initiative:v1:downtown-bike-lanes:create'
    )
  );

  // Message 3: Simple test message
  messages.push(await generateMessageVector('simple_message', 'test'));

  const vectors = {
    _comment:
      'Shared test vectors for cross-language signing verification. Generated by loom-core JS, verified by Python.',
    privateKey: PRIVATE_KEY_HEX,
    publicKey,
    events,
    messages,
  };

  const outputPath = join(__dirname, '..', 'test-vectors.json');
  writeFileSync(outputPath, JSON.stringify(vectors, null, 2) + '\n');
  console.log(`\nWrote ${events.length} event vectors and ${messages.length} message vectors to test-vectors.json`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
