"""Attestation signing server.

Two endpoints:
  POST /sign    — Sign an attestation event (authenticated)
  GET  /health  — Public key and status (unauthenticated)

This is the entire surface area. An organization runs this service,
CivicOS's relay calls /sign when one of their codes is redeemed,
and the signed attestation event goes back to the resident.
"""

import hashlib
import hmac
import logging
import os
import time
from datetime import datetime, timezone

from pydantic import BaseModel, Field

from civicos_signer.crypto import IssuerKeyPair, sign_attestation

logger = logging.getLogger("civicos-signer")


# --- Request/Response Models ---


class SignRequest(BaseModel):
    """Request from the relay to sign an attestation."""

    subject_pubkey: str = Field(description="The resident's public key (hex)")
    jurisdiction: str = Field(description="Jurisdiction code (e.g., city-san-rafael)")
    attestation_type: str = Field(default="physical", description="Attestation method")
    code: str = Field(description="The attestation code being redeemed (for audit log)")
    relay_timestamp: int = Field(description="Unix timestamp from the relay (replay protection)")


class SignResponse(BaseModel):
    """Signed attestation event returned to the relay."""

    attestation_event: dict


class HealthResponse(BaseModel):
    """Public status and identity."""

    status: str = "ok"
    issuer_pubkey: str
    jurisdiction: str
    organization: str
    version: str = "0.1.0"


# --- Server ---


def create_app(
    issuer: IssuerKeyPair,
    jurisdiction: str,
    organization: str,
    bearer_token: str,
    allowed_types: list[str] | None = None,
):
    """Create the FastAPI app for this issuer.

    Args:
        issuer: The organization's signing keypair.
        jurisdiction: Which jurisdiction this issuer serves.
        organization: Human-readable org name (for /health).
        bearer_token: Shared secret with the CivicOS relay.
        allowed_types: Attestation types this issuer can sign (default: ["physical"]).
    """
    from fastapi import FastAPI, HTTPException, Header

    app = FastAPI(
        title=f"CivicOS Signer — {organization}",
        description="Attestation signing service",
        version="0.1.0",
    )

    _allowed_types = set(allowed_types or ["physical"])
    _token_hash = hashlib.sha256(bearer_token.encode()).hexdigest()

    # Audit log: append-only record of every signing operation
    _audit_log: list[dict] = []

    def _verify_bearer(authorization: str = Header()) -> None:
        """Verify the relay's bearer token."""
        if not authorization.startswith("Bearer "):
            raise HTTPException(status_code=401, detail="Missing bearer token")
        provided = authorization[7:]
        provided_hash = hashlib.sha256(provided.encode()).hexdigest()
        if not hmac.compare_digest(provided_hash, _token_hash):
            raise HTTPException(status_code=401, detail="Invalid bearer token")

    @app.post("/sign", response_model=SignResponse)
    async def sign(request: SignRequest, authorization: str = Header()):
        """Sign an attestation event.

        Called by the CivicOS relay when a resident redeems a code
        generated by this organization.
        """
        _verify_bearer(authorization)

        # Validate attestation type
        if request.attestation_type not in _allowed_types:
            raise HTTPException(
                status_code=400,
                detail=f"Attestation type '{request.attestation_type}' not allowed. "
                f"Allowed: {sorted(_allowed_types)}",
            )

        # Replay protection: reject requests older than 60 seconds
        now = int(time.time())
        if abs(now - request.relay_timestamp) > 60:
            raise HTTPException(status_code=400, detail="Request too old (>60s)")

        # Validate subject pubkey format
        if len(request.subject_pubkey) != 64:
            raise HTTPException(status_code=400, detail="Invalid subject pubkey length")
        try:
            bytes.fromhex(request.subject_pubkey)
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid subject pubkey hex")

        # Sign
        attestation_event = sign_attestation(
            issuer=issuer,
            subject_pubkey=request.subject_pubkey,
            jurisdiction=jurisdiction,
            attestation_type=request.attestation_type,
        )

        # Audit log
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "subject_pubkey": request.subject_pubkey[:16] + "...",
            "code": request.code[:8] + "...",
            "attestation_type": request.attestation_type,
            "event_id": attestation_event["id"][:16] + "...",
        }
        _audit_log.append(entry)
        logger.info(f"Signed attestation: {entry}")

        return SignResponse(attestation_event=attestation_event)

    @app.get("/health", response_model=HealthResponse)
    async def health():
        """Public endpoint: who is this issuer?

        Returns the issuer's public key so relays can register it
        in their trusted issuer set. No authentication required.
        """
        return HealthResponse(
            issuer_pubkey=issuer.public_key_hex,
            jurisdiction=jurisdiction,
            organization=organization,
        )

    @app.get("/audit")
    async def audit(authorization: str = Header()):
        """Authenticated endpoint: signing audit log.

        Returns the list of all signing operations performed.
        Truncated pubkeys/codes for privacy.
        """
        _verify_bearer(authorization)
        return {"entries": _audit_log, "total": len(_audit_log)}

    return app


def run_from_env():
    """Start the signer server from environment variables.

    Required env vars:
        CIVICOS_SIGNER_PRIVATE_KEY  — Issuer private key (hex)
        CIVICOS_SIGNER_JURISDICTION — Jurisdiction code
        CIVICOS_SIGNER_ORGANIZATION — Organization name
        CIVICOS_SIGNER_BEARER_TOKEN — Shared secret with relay

    Optional:
        CIVICOS_SIGNER_ALLOWED_TYPES — Comma-separated (default: physical)
        CIVICOS_SIGNER_PORT          — Port (default: 8850)
        CIVICOS_SIGNER_HOST          — Host (default: 0.0.0.0)
    """
    import uvicorn

    private_key = os.environ.get("CIVICOS_SIGNER_PRIVATE_KEY")
    jurisdiction = os.environ.get("CIVICOS_SIGNER_JURISDICTION")
    organization = os.environ.get("CIVICOS_SIGNER_ORGANIZATION")
    bearer_token = os.environ.get("CIVICOS_SIGNER_BEARER_TOKEN")

    missing = []
    if not private_key:
        missing.append("CIVICOS_SIGNER_PRIVATE_KEY")
    if not jurisdiction:
        missing.append("CIVICOS_SIGNER_JURISDICTION")
    if not organization:
        missing.append("CIVICOS_SIGNER_ORGANIZATION")
    if not bearer_token:
        missing.append("CIVICOS_SIGNER_BEARER_TOKEN")
    if missing:
        print(f"Error: missing required env vars: {', '.join(missing)}")
        raise SystemExit(1)

    allowed_types_str = os.environ.get("CIVICOS_SIGNER_ALLOWED_TYPES", "physical")
    allowed_types = [t.strip() for t in allowed_types_str.split(",")]

    issuer = IssuerKeyPair.from_private_key(private_key)
    print(f"CivicOS Signer starting")
    print(f"  Organization: {organization}")
    print(f"  Jurisdiction: {jurisdiction}")
    print(f"  Issuer pubkey: {issuer.public_key_hex}")
    print(f"  Allowed types: {allowed_types}")

    app = create_app(
        issuer=issuer,
        jurisdiction=jurisdiction,
        organization=organization,
        bearer_token=bearer_token,
        allowed_types=allowed_types,
    )

    port = int(os.environ.get("CIVICOS_SIGNER_PORT", "8850"))
    host = os.environ.get("CIVICOS_SIGNER_HOST", "0.0.0.0")

    uvicorn.run(app, host=host, port=port)
