"""
Cross-language signing verification tests.

Reads test vectors generated by loom-core (JS) and verifies that Python
produces identical intermediate values AND can verify JS-produced signatures.

This is the critical interop test: if both sides agree on serialization,
event IDs, and message hashes, AND Python accepts JS signatures, then
cross-language signing is proven correct.
"""

import hashlib
import json
from pathlib import Path

import pytest

from civicos_relay.nostr.crypto import (
    serialize_event_for_id,
    compute_event_id,
    verify_event_signature,
)
from civicos_relay.voice.crypto import verify_signature

VECTORS_PATH = Path(__file__).resolve().parent / "../../loom-core/test-vectors.json"


@pytest.fixture(scope="module")
def vectors():
    """Load shared test vectors generated by JS."""
    assert VECTORS_PATH.exists(), f"Test vectors not found at {VECTORS_PATH}"
    with open(VECTORS_PATH) as f:
        return json.load(f)


class TestPublicKeyAgreement:
    """Verify both runtimes agree on the secp256k1 generator point."""

    def test_known_keypair(self, vectors):
        """Private key 0x01 produces the expected public key."""
        from coincurve import PrivateKey

        pk = PrivateKey(bytes.fromhex(vectors["privateKey"]))
        # x-only public key: skip the 02/03 prefix byte
        compressed = pk.public_key.format(compressed=True)
        x_only = compressed[1:].hex()
        assert x_only == vectors["publicKey"]


class TestEventSerialization:
    """Verify Python serialization matches JS for all event vectors."""

    def test_serialization_matches(self, vectors):
        for v in vectors["events"]:
            u = v["unsigned"]
            serialized = serialize_event_for_id(
                u["pubkey"], u["created_at"], u["kind"], u["tags"], u["content"]
            )
            assert serialized == v["expectedSerialized"], (
                f"Serialization mismatch for {v['name']}"
            )

    def test_event_id_matches(self, vectors):
        for v in vectors["events"]:
            u = v["unsigned"]
            event_id = compute_event_id(
                u["pubkey"], u["created_at"], u["kind"], u["tags"], u["content"]
            )
            assert event_id == v["expectedEventId"], (
                f"Event ID mismatch for {v['name']}"
            )


class TestEventSignatureVerification:
    """Verify Python accepts JS-produced Schnorr signatures on events."""

    def test_js_event_signatures_verify(self, vectors):
        for v in vectors["events"]:
            result = verify_event_signature(
                v["expectedEventId"], vectors["publicKey"], v["expectedSig"]
            )
            assert result, f"Python rejected JS signature for event {v['name']}"

    def test_rejects_wrong_event_id(self, vectors):
        v = vectors["events"][0]
        fake_id = "0" * 64
        assert not verify_event_signature(
            fake_id, vectors["publicKey"], v["expectedSig"]
        )

    def test_rejects_wrong_pubkey(self, vectors):
        v = vectors["events"][0]
        fake_key = "a" * 64
        assert not verify_event_signature(
            v["expectedEventId"], fake_key, v["expectedSig"]
        )


class TestMessageHashAgreement:
    """Verify Python SHA-256 matches JS for all message vectors."""

    def test_message_hash_matches(self, vectors):
        for v in vectors["messages"]:
            msg_hash = hashlib.sha256(v["message"].encode("utf-8")).hexdigest()
            assert msg_hash == v["expectedHash"], (
                f"Message hash mismatch for {v['name']}"
            )


class TestMessageSignatureVerification:
    """Verify Python accepts JS-produced Schnorr signatures on messages."""

    def test_js_message_signatures_verify(self, vectors):
        for v in vectors["messages"]:
            result = verify_signature(
                vectors["publicKey"], v["expectedSig"], v["message"]
            )
            assert result, f"Python rejected JS signature for message {v['name']}"

    def test_rejects_wrong_message(self, vectors):
        v = vectors["messages"][0]
        assert not verify_signature(
            vectors["publicKey"], v["expectedSig"], "wrong message"
        )

    def test_rejects_wrong_pubkey(self, vectors):
        v = vectors["messages"][0]
        fake_key = "a" * 64
        assert not verify_signature(fake_key, v["expectedSig"], v["message"])
